apiVersion: v1
kind: Service
metadata:
  name: pycon-flask
  labels:
    name: pycon-flask
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: pycon-flask